// This file is auto-generated by `yarn gen-bindings`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	settingsGet: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, valueJson: string) => typedError<null, string>(__TAURI_INVOKE("settings_set", { key, valueJson })),
	settingsDelete: (key: string) => typedError<boolean, string>(__TAURI_INVOKE("settings_delete", { key })),
	settingsAll: () => typedError<{ [key in string]: string }, string>(__TAURI_INVOKE("settings_all")),
	voiceStart: (opts: VoiceStartOpts) => typedError<string, string>(__TAURI_INVOKE("voice_start", { opts })),
	voiceStop: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("voice_stop", { sessionId })),
	voicePushFrame: (sessionId: string, pcm: number[]) => typedError<null, string>(__TAURI_INVOKE("voice_push_frame", { sessionId, pcm })),
	buddyGetActive: () => __TAURI_INVOKE<BuddyDisplayInfo>("buddy_get_active"),
	buddyList: () => __TAURI_INVOKE<BuddyDisplayInfo[]>("buddy_list"),
	authStatus: () => __TAURI_INVOKE<AuthStatus>("auth_status"),
	authStart: () => typedError<AuthStartResponse, string>(__TAURI_INVOKE("auth_start")),
	authCancel: () => typedError<null, string>(__TAURI_INVOKE("auth_cancel")),
	authSignOut: () => typedError<null, string>(__TAURI_INVOKE("auth_sign_out")),
};

/* Types */
// Smoke/introspection type — lets the Vue app display the packaged version.
export type AppInfo = {
	version: string,
};

/**
 *  Payload returned synchronously from `auth_start` so the UI can show the
 *  user code immediately without waiting for the first `auth://status` event.
 */
export type AuthStartResponse = {
	user_code: string,
	verification_uri: string,
	verification_uri_complete: string,
	expires_in: number,
	interval: number,
};

/**
 *  Snapshot of the current flow state. `kind` drives the UI switch in
 *  `ConnectionPanel.vue`.
 */
export type AuthStatus = { kind: "idle" } | { kind: "pending"; user_code: string; verification_uri: string; verification_uri_complete: string; expires_at_ms: number } | { kind: "authenticated" } | { kind: "error"; code: string; message: string };

export type BuddyDisplayInfo = {
	id: string,
	name: string,
	/**
	 *  Relative path served from the Vue dev/build output — the frontend
	 *  already bundles a default VRM under `src/three/assets/vrm/...`.
	 */
	model_url: string,
	emotion: string,
};

export type VoiceStartOpts = {
	buddy_id: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

